dist: xenial
language: python
python:
- 3.4
- 3.5
- 3.6
- 3.7
- nightly
before_install:
- apt-get update && apt-get install -y --no-install-recommends python3-dev libxml2-dev libxslt1-dev libxslt-dev libyajl2
- pip install -U pip setuptools wheel
- pip install -r requirements-dev.txt
install: pip install -e .
script: coverage run --source payit $(which nosetests)
after_success: if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then travis_retry coveralls; fi
